### ISSUE TITLE
vm/z80cpu folder appears to be missing

### ISSUE THREAD

**Issue by ravn** [durgadas311/virtual-cpm#3]
I tried building the sources under MacOS.

Apparently the vm/z80cpu sources are not there, so it fails.  Is there an additional step needed to get buildable sources?

**Comment by durgadas311** [comment]
Yes, an external package is needed - which I have not mentioned here. I need to provide some instructions for building this. I will work on that. I need to publish the z80cpu code, will work on that, too. In the mean time, this should work: http://sebhc.durgadas.com/mms89/z80cpu.tgz

**Comment by durgadas311** [comment]
Oh, unpack the tarball in the 'vm' directory (or symlink to it at some other location). Then, run 'make' in the z80cpu subdirectory.

**Comment by durgadas311** [comment]
I have published z80cpu now, and added instructions to this README. Note, it should not usually be required to rebuild this project. The JAR file should run on any platform that has a JAVA runtime.

**Comment by ravn** [comment]
Thank you.   I like that you did the stuff in Java and I'll have a closer look at your network code.  

You may want to have a look at git submodules to link your sources together across repositories and/or Maven layout to make it easy for others to get started with your work.  You don't need to publish to Maven Central or others, if you just very explicitly say in the README.md to go to project X and run "mvn install" before building this project.

**Comment by durgadas311** [comment]
Yeah, lots of improvement to be made. submodules is a good way to go, just need to do that... just did a hurried publish to get this out there.
